/* js/layers.js — AUTO-GENERATED by tools/gen_layers.mjs. Do not edit by hand.
   v3 depth ramp + foreground props per scene (consumed by the engine). */
window.GAME = window.GAME || {};
GAME.LAYERS = {
  "deep_forest": {
    "depth": {
      "horizon": 150,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "big_tree_left",
        "img": "prop_deep_forest_big_tree_left",
        "x": 20,
        "baseline": 178,
        "units": 4,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 1,
          "speed": 0.25,
          "fps": 0
        }
      },
      {
        "name": "big_tree_right",
        "img": "prop_deep_forest_big_tree_right",
        "x": 302,
        "baseline": 182,
        "units": 4.4,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 1,
          "speed": 0.22,
          "fps": 0
        }
      },
      {
        "name": "mossy_log",
        "img": "prop_deep_forest_mossy_log",
        "x": 256,
        "baseline": 176,
        "units": 0.85,
        "layer": "front",
        "anim": null
      },
      {
        "name": "fork_signpost",
        "img": "prop_deep_forest_fork_signpost",
        "x": 168,
        "baseline": 162,
        "units": 1.3,
        "layer": "back",
        "anim": {
          "type": "sway",
          "amp": 2,
          "speed": 0.5,
          "fps": 0
        }
      }
    ]
  },
  "finale": {
    "depth": {
      "horizon": 162,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "bed_with_granny",
        "img": "prop_finale_bed_with_granny",
        "x": 162,
        "baseline": 158,
        "units": 1.1,
        "layer": "back",
        "anim": {
          "type": "bob",
          "amp": 1,
          "speed": 0.6,
          "fps": 0
        }
      },
      {
        "name": "footboard_post",
        "img": "prop_finale_footboard_post",
        "x": 112,
        "baseline": 176,
        "units": 0.95,
        "layer": "front",
        "anim": null
      },
      {
        "name": "doorframe_edge",
        "img": "prop_finale_doorframe_edge",
        "x": 300,
        "baseline": 178,
        "units": 2.9,
        "layer": "front",
        "anim": null
      }
    ]
  },
  "forest_edge": {
    "depth": {
      "horizon": 150,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "fg_tree_left",
        "img": "prop_forest_edge_fg_tree_left",
        "x": 30,
        "baseline": 162,
        "units": 4.2,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 2.5,
          "speed": 0.4,
          "fps": 0
        }
      },
      {
        "name": "fg_tree_right",
        "img": "prop_forest_edge_fg_tree_right",
        "x": 308,
        "baseline": 160,
        "units": 4,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 2.5,
          "speed": 0.35,
          "fps": 0
        }
      },
      {
        "name": "log_pile",
        "img": "prop_forest_edge_log_pile",
        "x": 270,
        "baseline": 168,
        "units": 0.8,
        "layer": "front",
        "anim": null
      },
      {
        "name": "forest_sign",
        "img": "prop_forest_edge_forest_sign",
        "x": 100,
        "baseline": 152,
        "units": 1.7,
        "layer": "back",
        "anim": {
          "type": "sway",
          "amp": 1.5,
          "speed": 0.6,
          "fps": 0
        }
      }
    ]
  },
  "granny_ext": {
    "depth": {
      "horizon": 150,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "left_tree_trunk",
        "img": "prop_granny_ext_left_tree_trunk",
        "x": 18,
        "baseline": 200,
        "units": 3.3,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 1.5,
          "speed": 0.4,
          "fps": 0
        }
      },
      {
        "name": "garden_gnome",
        "img": "prop_granny_ext_garden_gnome",
        "x": 213,
        "baseline": 168,
        "units": 0.4,
        "layer": "front",
        "anim": {
          "type": "bob",
          "amp": 1,
          "speed": 0.6,
          "fps": 0
        }
      },
      {
        "name": "flower_bed_planter",
        "img": "prop_granny_ext_flower_bed_planter",
        "x": 70,
        "baseline": 172,
        "units": 0.4,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 2,
          "speed": 0.8,
          "fps": 0
        }
      }
    ]
  },
  "granny_int": {
    "depth": {
      "horizon": 158,
      "near": 1.15,
      "far": 0.82
    },
    "props": [
      {
        "name": "rocking_chair",
        "img": "prop_granny_int_rocking_chair",
        "x": 96,
        "baseline": 160,
        "units": 1.18,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 4,
          "speed": 0.8,
          "fps": 0
        }
      },
      {
        "name": "bed_footboard",
        "img": "prop_granny_int_bed_footboard",
        "x": 224,
        "baseline": 164,
        "units": 0.82,
        "layer": "front",
        "anim": null
      },
      {
        "name": "candle_table",
        "img": "prop_granny_int_candle_table",
        "x": 150,
        "baseline": 160,
        "units": 0.62,
        "layer": "back",
        "anim": null
      }
    ]
  },
  "hood": {
    "depth": {
      "horizon": 112,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "kiosk_stall",
        "img": "prop_hood_kiosk_stall",
        "x": 70,
        "baseline": 150,
        "units": 2,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 1.5,
          "speed": 0.5,
          "fps": 0
        }
      },
      {
        "name": "palm_tree",
        "img": "prop_hood_palm_tree",
        "x": 196,
        "baseline": 146,
        "units": 4,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 4,
          "speed": 0.6,
          "fps": 0
        }
      },
      {
        "name": "red_scooter",
        "img": "prop_hood_red_scooter",
        "x": 168,
        "baseline": 158,
        "units": 1,
        "layer": "front",
        "anim": null
      }
    ]
  },
  "intro": {
    "depth": {
      "horizon": 120,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "fg_tree_left",
        "img": "prop_intro_fg_tree_left",
        "x": 34,
        "baseline": 188,
        "units": 3.1,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 2.5,
          "speed": 0.35,
          "fps": 0
        }
      },
      {
        "name": "moon_disc",
        "img": "prop_intro_moon_disc",
        "x": 267,
        "baseline": 58,
        "units": 1.25,
        "layer": "back",
        "anim": {
          "type": "pulse",
          "amp": 0,
          "speed": 0.15,
          "fps": 0
        }
      },
      {
        "name": "mushroom_cluster",
        "img": "prop_intro_mushroom_cluster",
        "x": 22,
        "baseline": 178,
        "units": 0.3,
        "layer": "front",
        "anim": {
          "type": "bob",
          "amp": 1,
          "speed": 0.5,
          "fps": 0
        }
      }
    ]
  },
  "living_room": {
    "depth": {
      "horizon": 158,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "couch",
        "img": "prop_living_room_couch",
        "x": 135,
        "baseline": 154,
        "units": 0.85,
        "layer": "front",
        "anim": null
      },
      {
        "name": "crt_tv_stand",
        "img": "prop_living_room_crt_tv_stand",
        "x": 240,
        "baseline": 152,
        "units": 0.85,
        "layer": "front",
        "anim": null
      },
      {
        "name": "persian_rug",
        "img": "prop_living_room_persian_rug",
        "x": 162,
        "baseline": 188,
        "units": 0.5,
        "layer": "back",
        "anim": null
      }
    ]
  },
  "river": {
    "depth": {
      "horizon": 156,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "reed_clump_right",
        "img": "prop_river_reed_clump_right",
        "x": 282,
        "baseline": 190,
        "units": 1.1,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 5,
          "speed": 0.7,
          "fps": 0
        }
      },
      {
        "name": "boulder_cluster_left",
        "img": "prop_river_boulder_cluster_left",
        "x": 34,
        "baseline": 192,
        "units": 1,
        "layer": "front",
        "anim": null
      },
      {
        "name": "grass_rock_tuft_front",
        "img": "prop_river_grass_rock_tuft_front",
        "x": 168,
        "baseline": 200,
        "units": 0.6,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 3,
          "speed": 1.1,
          "fps": 0
        }
      }
    ]
  },
  "room_red": {
    "depth": {
      "horizon": 152,
      "near": 1.15,
      "far": 0.78
    },
    "props": [
      {
        "name": "bed_footboard",
        "img": "prop_room_red_bed_footboard",
        "x": 52,
        "baseline": 172,
        "units": 0.78,
        "layer": "front",
        "anim": null
      },
      {
        "name": "clutter_pile_backpack",
        "img": "prop_room_red_clutter_pile_backpack",
        "x": 108,
        "baseline": 180,
        "units": 0.42,
        "layer": "front",
        "anim": null
      }
    ]
  },
  "wolf_garden": {
    "depth": {
      "horizon": 158,
      "near": 1.12,
      "far": 0.78
    },
    "props": [
      {
        "name": "left_tree",
        "img": "prop_wolf_garden_left_tree",
        "x": 10,
        "baseline": 200,
        "units": 4.2,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 1.5,
          "speed": 0.4,
          "fps": 0
        }
      },
      {
        "name": "scarecrow",
        "img": "prop_wolf_garden_scarecrow",
        "x": 130,
        "baseline": 168,
        "units": 1.5,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 2,
          "speed": 0.6,
          "fps": 0
        }
      },
      {
        "name": "watering_can",
        "img": "prop_wolf_garden_watering_can",
        "x": 64,
        "baseline": 178,
        "units": 0.3,
        "layer": "front",
        "anim": null
      },
      {
        "name": "wolf_hut",
        "img": "prop_wolf_garden_wolf_hut",
        "x": 282,
        "baseline": 130,
        "units": 2.6,
        "layer": "back",
        "anim": null
      }
    ]
  }
};
