/* js/layers.js — AUTO-GENERATED by tools/gen_layers.mjs. Do not edit by hand.
   v3 depth ramp + foreground props per scene (consumed by the engine). */
window.GAME = window.GAME || {};
GAME.LAYERS = {
  "deep_forest": {
    "depth": {
      "horizon": 150,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "big_tree_left",
        "img": "prop_deep_forest_big_tree_left",
        "x": 22,
        "baseline": 168,
        "scale": 0.95,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 1,
          "speed": 0.25,
          "fps": 0
        }
      },
      {
        "name": "big_tree_right",
        "img": "prop_deep_forest_big_tree_right",
        "x": 298,
        "baseline": 166,
        "scale": 0.98,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 1,
          "speed": 0.22,
          "fps": 0
        }
      },
      {
        "name": "mossy_log",
        "img": "prop_deep_forest_mossy_log",
        "x": 225,
        "baseline": 150,
        "scale": 0.42,
        "layer": "front",
        "anim": null
      },
      {
        "name": "fork_signpost",
        "img": "prop_deep_forest_fork_signpost",
        "x": 156,
        "baseline": 146,
        "scale": 0.22,
        "layer": "back",
        "anim": {
          "type": "sway",
          "amp": 2,
          "speed": 0.5,
          "fps": 0
        }
      }
    ]
  },
  "finale": {
    "depth": {
      "horizon": 162,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "bed_with_granny",
        "img": "prop_finale_bed_with_granny",
        "x": 162,
        "baseline": 158,
        "scale": 0.42,
        "layer": "back",
        "anim": {
          "type": "bob",
          "amp": 1,
          "speed": 0.6,
          "fps": 0
        }
      },
      {
        "name": "footboard_post",
        "img": "prop_finale_footboard_post",
        "x": 112,
        "baseline": 176,
        "scale": 0.5,
        "layer": "front",
        "anim": null
      },
      {
        "name": "doorframe_edge",
        "img": "prop_finale_doorframe_edge",
        "x": 300,
        "baseline": 178,
        "scale": 0.92,
        "layer": "front",
        "anim": null
      }
    ]
  },
  "forest_edge": {
    "depth": {
      "horizon": 150,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "fg_tree_left",
        "img": "prop_forest_edge_fg_tree_left",
        "x": 38,
        "baseline": 158,
        "scale": 0.95,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 2.5,
          "speed": 0.4,
          "fps": 0
        }
      },
      {
        "name": "fg_tree_right",
        "img": "prop_forest_edge_fg_tree_right",
        "x": 302,
        "baseline": 156,
        "scale": 0.9,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 2.5,
          "speed": 0.35,
          "fps": 0
        }
      },
      {
        "name": "log_pile",
        "img": "prop_forest_edge_log_pile",
        "x": 265,
        "baseline": 152,
        "scale": 0.28,
        "layer": "front",
        "anim": null
      },
      {
        "name": "forest_sign",
        "img": "prop_forest_edge_forest_sign",
        "x": 152,
        "baseline": 136,
        "scale": 0.22,
        "layer": "back",
        "anim": {
          "type": "sway",
          "amp": 1.5,
          "speed": 0.6,
          "fps": 0
        }
      }
    ]
  },
  "granny_ext": {
    "depth": {
      "horizon": 150,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "left_tree_trunk",
        "img": "prop_granny_ext_left_tree_trunk",
        "x": 18,
        "baseline": 196,
        "scale": 1,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 1.5,
          "speed": 0.4,
          "fps": 0
        }
      },
      {
        "name": "garden_gnome",
        "img": "prop_granny_ext_garden_gnome",
        "x": 213,
        "baseline": 159,
        "scale": 0.22,
        "layer": "front",
        "anim": {
          "type": "bob",
          "amp": 1,
          "speed": 0.6,
          "fps": 0
        }
      },
      {
        "name": "flower_bed_planter",
        "img": "prop_granny_ext_flower_bed_planter",
        "x": 63,
        "baseline": 164,
        "scale": 0.12,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 2,
          "speed": 0.8,
          "fps": 0
        }
      }
    ]
  },
  "granny_int": {
    "depth": {
      "horizon": 158,
      "near": 1.15,
      "far": 0.82
    },
    "props": [
      {
        "name": "rocking_chair",
        "img": "prop_granny_int_rocking_chair",
        "x": 98,
        "baseline": 156,
        "scale": 0.3,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 4,
          "speed": 0.8,
          "fps": 0
        }
      },
      {
        "name": "bed_footboard",
        "img": "prop_granny_int_bed_footboard",
        "x": 201,
        "baseline": 158,
        "scale": 0.34,
        "layer": "front",
        "anim": null
      },
      {
        "name": "candle_table",
        "img": "prop_granny_int_candle_table",
        "x": 150,
        "baseline": 158,
        "scale": 0.22,
        "layer": "back",
        "anim": null
      }
    ]
  },
  "hood": {
    "depth": {
      "horizon": 112,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "kiosk_stall",
        "img": "prop_hood_kiosk_stall",
        "x": 70,
        "baseline": 150,
        "scale": 0.46,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 1.5,
          "speed": 0.5,
          "fps": 0
        }
      },
      {
        "name": "palm_tree",
        "img": "prop_hood_palm_tree",
        "x": 196,
        "baseline": 146,
        "scale": 0.78,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 4,
          "speed": 0.6,
          "fps": 0
        }
      },
      {
        "name": "red_scooter",
        "img": "prop_hood_red_scooter",
        "x": 168,
        "baseline": 158,
        "scale": 0.3,
        "layer": "front",
        "anim": null
      }
    ]
  },
  "intro": {
    "depth": {
      "horizon": 120,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "fg_tree_left",
        "img": "prop_intro_fg_tree_left",
        "x": 34,
        "baseline": 188,
        "scale": 1,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 2.5,
          "speed": 0.35,
          "fps": 0
        }
      },
      {
        "name": "moon_disc",
        "img": "prop_intro_moon_disc",
        "x": 252,
        "baseline": 60,
        "scale": 0.18,
        "layer": "back",
        "anim": {
          "type": "pulse",
          "amp": 0,
          "speed": 0.15,
          "fps": 0
        }
      },
      {
        "name": "mushroom_cluster",
        "img": "prop_intro_mushroom_cluster",
        "x": 22,
        "baseline": 178,
        "scale": 0.14,
        "layer": "front",
        "anim": {
          "type": "bob",
          "amp": 1,
          "speed": 0.5,
          "fps": 0
        }
      }
    ]
  },
  "living_room": {
    "depth": {
      "horizon": 158,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "couch",
        "img": "prop_living_room_couch",
        "x": 135,
        "baseline": 154,
        "scale": 0.22,
        "layer": "front",
        "anim": null
      },
      {
        "name": "crt_tv_stand",
        "img": "prop_living_room_crt_tv_stand",
        "x": 240,
        "baseline": 152,
        "scale": 0.3,
        "layer": "front",
        "anim": null
      },
      {
        "name": "persian_rug",
        "img": "prop_living_room_persian_rug",
        "x": 162,
        "baseline": 188,
        "scale": 0.12,
        "layer": "back",
        "anim": null
      }
    ]
  },
  "river": {
    "depth": {
      "horizon": 156,
      "near": 1.15,
      "far": 0.7
    },
    "props": [
      {
        "name": "reed_clump_right",
        "img": "prop_river_reed_clump_right",
        "x": 270,
        "baseline": 188,
        "scale": 0.34,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 5,
          "speed": 0.7,
          "fps": 0
        }
      },
      {
        "name": "boulder_cluster_left",
        "img": "prop_river_boulder_cluster_left",
        "x": 40,
        "baseline": 190,
        "scale": 0.28,
        "layer": "front",
        "anim": null
      },
      {
        "name": "grass_rock_tuft_front",
        "img": "prop_river_grass_rock_tuft_front",
        "x": 158,
        "baseline": 198,
        "scale": 0.18,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 3,
          "speed": 1.1,
          "fps": 0
        }
      }
    ]
  },
  "room_red": {
    "depth": {
      "horizon": 152,
      "near": 1.15,
      "far": 0.78
    },
    "props": [
      {
        "name": "bed_footboard",
        "img": "prop_room_red_bed_footboard",
        "x": 56,
        "baseline": 164,
        "scale": 0.34,
        "layer": "front",
        "anim": null
      },
      {
        "name": "clutter_pile_backpack",
        "img": "prop_room_red_clutter_pile_backpack",
        "x": 168,
        "baseline": 160,
        "scale": 0.18,
        "layer": "front",
        "anim": null
      }
    ]
  },
  "wolf_garden": {
    "depth": {
      "horizon": 158,
      "near": 1.12,
      "far": 0.78
    },
    "props": [
      {
        "name": "left_tree",
        "img": "prop_wolf_garden_left_tree",
        "x": 16,
        "baseline": 196,
        "scale": 0.98,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 1.5,
          "speed": 0.4,
          "fps": 0
        }
      },
      {
        "name": "scarecrow",
        "img": "prop_wolf_garden_scarecrow",
        "x": 130,
        "baseline": 150,
        "scale": 0.42,
        "layer": "front",
        "anim": {
          "type": "sway",
          "amp": 2,
          "speed": 0.6,
          "fps": 0
        }
      },
      {
        "name": "watering_can",
        "img": "prop_wolf_garden_watering_can",
        "x": 64,
        "baseline": 162,
        "scale": 0.13,
        "layer": "front",
        "anim": null
      },
      {
        "name": "wolf_hut",
        "img": "prop_wolf_garden_wolf_hut",
        "x": 282,
        "baseline": 110,
        "scale": 0.46,
        "layer": "back",
        "anim": null
      }
    ]
  }
};
