#!/usr/bin/env node
/* gen_layers.mjs — read docs/layers/*.json -> emit js/layers.js (GAME.LAYERS).
 * Centralizes v3 depth + foreground props so scene files need no edits.
 */
import { readdirSync, readFileSync, writeFileSync } from 'fs';

const dir = 'docs/layers';
const files = readdirSync(dir).filter(f => f.endsWith('.json'));
const out = {};
for (const f of files) {
  let spec;
  try { spec = JSON.parse(readFileSync(`${dir}/${f}`, 'utf8')); }
  catch (e) { console.error('skip (bad json):', f, e.message); continue; }
  const id = spec.id || f.replace('.json', '');
  const d = spec.depth || {};
  const UNIT = 64;  // must match engine UNIT
  const props = (spec.props || []).map(p => ({
    name: p.name,
    img: 'prop_' + id + '_' + p.name,
    x: p.x, baseline: p.baseline,
    // convert legacy frame-fraction scale -> character-height units (initial estimate; calibrated later)
    units: p.units != null ? p.units : (p.scale != null ? +((p.scale * 200) / UNIT).toFixed(2) : 1.5),
    layer: (p.role === 'midground') ? 'back' : 'front',
    anim: p.anim && p.anim.type && p.anim.type !== 'none' ? {
      type: p.anim.type,
      amp: p.anim.amp != null ? p.anim.amp : (p.anim.type === 'sway' ? 3 : 2),
      speed: p.anim.speed != null ? p.anim.speed : 1,
      fps: p.anim.fps, phase: p.anim.phase,
    } : null,
  }));
  out[id] = {
    depth: { horizon: d.horizon != null ? d.horizon : 150, near: d.nearScale != null ? d.nearScale : 1.1, far: d.farScale != null ? d.farScale : 0.75 },
    props,
  };
  if (Array.isArray(spec.walkpoly) && spec.walkpoly.length >= 3) out[id].walkpoly = spec.walkpoly;
}
const js = `/* js/layers.js — AUTO-GENERATED by tools/gen_layers.mjs. Do not edit by hand.
   v3 depth ramp + foreground props per scene (consumed by the engine). */
window.GAME = window.GAME || {};
GAME.LAYERS = ${JSON.stringify(out, null, 2)};
`;
writeFileSync('js/layers.js', js);
const counts = Object.entries(out).map(([k, v]) => `${k}:${v.props.length}`).join(', ');
console.log('wrote js/layers.js with', Object.keys(out).length, 'scenes ->', counts);
